### ISSUE TITLE
Ability to map controls to all keys

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/fmsx-libretro#10]
For example I play a game ([Hanafuda by Toshiba EMI](https://www.youtube.com/watch?v=Gx6-HmDUeL0)) where I need to select difficulty using keys 1,2,3 or select a card using 1,2,3,4,5,6,7,8 but I cannot do this so I cannot proceed.

It would be good if keys from the whole MSX keyboard are available for mapping.

Using RA 1.4.1 on New3DS

**Comment by gingerbeardman** [comment]
@twinaphex @fr500  did this core benefit from the recent keyboard remapping UI change?

**Comment by cayce-msx** [comment]
@gingerbeardman could you share some details about "the recent keyboard remapping UI change"? I have no clue what those are. With a bit of context I might be able to find out, by digging thru the code of RetroArch.

**Comment by gingerbeardman** [comment]
Thanks for asking, I have sat here for a few minutes and I cannot recall what those were. I also checked blog posts and found this:

https://www.libretro.com/index.php/retroarch-1-7-2-released/

> **Input remapping system improvements**
> The input remapping system (available from Quick Menu -> Controls) had many obvious limitations previously. Some of these included:
> 
> It was not possible to map keyboard from more than one gamepad (for instance with Dosbox)
> It was not possible to map more than one button to the same action
> It was not possible to unmap buttons or analogs
> It was not possible to map a button to trigger an analog response (for instance, in an N64 emulator, running in Super Mario 64 with the D-pad)
> It was not possible to map an analog to another analog
> It was not possible to map an analog to produce a button response
> Most of these restrictions have now been lifted at long last thanks to radius, and the visual representation is also much improved now.
> 
> To read more about this, also visit the [related forum thread here](https://forums.libretro.com/t/new-input-remapping-menu/15584).
> 
> Do note that all your existing remap files are now obsolete, and you should start from scratch. This was a necessary evil unfortunately in order to progress.

**Comment by cayce-msx** [comment]
I think I know what this provides, but it doesn't solve your request. I.e., you can only remap (permute, if you will) keys that are already defined. I tried but cannot add any extra keys. This'll have to be done inside the core. I'll give it a spin and see what autechre says about it.
