### ISSUE TITLE
MSX-MUSIC YM2413 emulation

### ISSUE THREAD

**Issue by freq-mod** [libretro/fmsx-libretro#102]
It's more of a request - is it possible to improve, or add proper YM2413 emulation? Right now it's just square waves, it sounds awful.

**Comment by freq-mod** [comment]
this fork has a more proper YM2413 emulation 🤔 https://github.com/pthalin/bittboy-msx/blob/master/src/YM2413.c

**Comment by gingerbeardman** [comment]
But that file is an old version of what is already included: https://github.com/libretro/fmsx-libretro/blob/master/EMULib/YM2413.c

So could it be a settings/configuration issue your end?

**Comment by freq-mod** [comment]
This file doesn't have built-in syntheszier parameters (`static const byte Synth2413`), so no.

**Comment by gingerbeardman** [comment]
That was removed as part of the removal of MIDI logging.

https://github.com/libretro/fmsx-libretro/commit/45b120f846d530bdc2cede87e8263ea6d883dd96#diff-29f62c658b938a727012ecfab3bed3bf35d98ae385ecb487240a6c3a3f9217a9

@freq-mod seeing as you have some experience with this, if you could advise @cayce-msx on how that broke things that would be appreciated!

**Comment by freq-mod** [comment]
everything after line 55 should have never been removed. Yamaha YM2413 chip 15 built-in FM tones + 5 built-in FM drums. That's the feature of a chip, not a MIDI bloat.

**Comment by cayce-msx** [comment]
Well, FM-PAC emulation is indeed very poor in fMSX. Also in the standalone product. Indeed, just triangle waves. Autechre wanted all MIDI code to be removed - which is a good thing, because MIDI output in fMSX/Win _also_ doesn't sound very much like a true FM-PAC. So I did. The Synth2413 constant actually isn't used in fMSX 6.0 (Unix source code from komkon.org) itself.

I was contemplating copying over some code from openMSX for this. (I have no clue how hard that would be - openMSX has a completely different approach to MSX emulation) Also, as the number of open issues keeps growing in stead of diminishing, I'm not sure when I'll get around to it.

**Comment by cayce-msx** [comment]
So yeah, I'm really curious what Synth2413 is doing in fMSX. Maybe Marat put that in as a first step but never completed it. AFAIK fMSX/Win also sounds exactly the same - but I can't be sure, as the fMSX/Win code is not open.

There's just 2 hits in the fMSX/X 6.0 code searching on Synth2413:

/** Synth2413() **********************************************/
static const byte Synth2413[19*16] =

That's all.. So it can't be used at all. It was removed on purpose; it's dead code.

**Comment by freq-mod** [comment]
the fork that I linked before had YM2413 working

**Comment by cayce-msx** [comment]
That's awesome! That name sounds familiar, I think I saw it in bluemsx and/or openMSX code. I'll try and merge that branch. Unless you want to have a go at that? PRs are always welcome.

**Comment by freq-mod** [comment]
the one in this fork in extremely ancient (2001) and outdated. It's best to use whatever openMSX uses, or at least, the upstream from https://github.com/digital-sound-antiques/emu2413

**Comment by freq-mod** [comment]
I may take a closer look at it soon-ish... although with my current C(++) skills, I can't promise anything.

**Comment by cayce-msx** [comment]
One thing to take into account is that better FM-PAC emulation might be a performance drain for low end devices. Best to add an option to switch current/new behaviour.

**Comment by freq-mod** [comment]
ok, so first problem - YM2413 emulation used in bittboy-msx port is dependent on this sdl library: https://github.com/pthalin/bittboy-msx/blob/master/src/SDLsnd.c

**Comment by cayce-msx** [comment]
@freq-mod it's finally there! You had to wait for 2+years on it, but once I started, it was actually smooth sailing. Indeed, as I predicted 2yrs back, it's slow - although my rpi3b has no problems keeping up.
I've used the original NukeYKT code (v1.0.2) from https://github.com/nukeykt/Nuked-OPLL and peek at openMSX how they invoke it, as NukeYKT comes with no docs at all ;)

**Comment by freq-mod** [comment]
wow, great news!
