### ISSUE TITLE
Save state glitches in MSX2+ mode

### ISSUE THREAD

**Issue by ofry** [libretro/fmsx-libretro#107]
Test case: Knightmare III - Shalom game.

1) set MSX mode as MSX2+ in fMSX core options.
2) save state on title screen.
3) reset through Quick Menu.
4) Immediately load state.

Result:
![Knightmare III - Shalom (English) Beta 4-220104-123425](https://user-images.githubusercontent.com/11790863/148039404-8b586758-2e6f-46d6-b125-65b563e3bd64.png)

**Comment by cayce-msx** [comment]
@ofry nice find! I bet this one is fixed when PR 105 is merged. It's related to switching resolution when showing the MSX2 boot screen. Which is a bit odd, as you mention MSX2+. So there might still be a problem left, related to picking up core options incorrectly. 

So, please hold on until that PR is merged and released. Then retest & let me know.

**Comment by cayce-msx** [comment]
PRs are merged. Latest Win64 build is at https://buildbot.libretro.com/nightly/windows/x86_64/latest/fmsx_libretro.dll.zip

**Comment by ofry** [comment]
Bug is fixed, thank you!
