### ISSUE TITLE
Gradius 2 not working

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/fmsx-libretro#118]
Hello 

It seems that after latest scc upgrade regular Gradius 2, stopped working.

 Gradius 2. Nemesis 2 (1987)(Konami)[RC-751] 

https://www.planetemu.net/roms/msx-various-rom?page=G

Please can you take a look? @cayce-msx  

thx

**Comment by cayce-msx** [comment]
Starts fine for me (commit f97252b, ROM SHA1 ab30cdeaacbdf14e6366d43d881338178fc665cb, Linux, local build). Could you be a bit more specific? What are your RA settings? Mine:

fmsx_mode = "MSX2"
fmsx_video_mode = "NTSC"
fmsx_mapper_type_mode = "Guess"
fmsx_ram_pages = "Auto"
fmsx_vram_pages = "Auto"
fmsx_log_level = "Off"
fmsx_simbdos = "No"
fmsx_autospace = "No"
fmsx_allsprites = "No"
fmsx_font = "standard"
fmsx_flush_disk = "Never"
fmsx_hires = "Off"
fmsx_overscan = "No"
fmsx_game_master = "No"
fmsx_phantom_disk = "No"
fmsx_dos2 = "No"
fmsx_scci_megaram = "Yes"

**Comment by Kelvfimer** [comment]
Sorry @cayce-msx  my bad it was Gradius 2. Nemesis 2 (1987)(Konami)[SCC][RC-751] 

Latest commit https://github.com/libretro/fmsx-libretro/commit/f97252b233effdad837e91f40b78fe3058ea4cb1

fmsx_allsprites = "Yes"
fmsx_autospace = "No"
fmsx_custom_keyboard_a = "space"
fmsx_custom_keyboard_b = "enter"
fmsx_custom_keyboard_down = "down"
fmsx_custom_keyboard_l = "f2"
fmsx_custom_keyboard_l2 = "graph"
fmsx_custom_keyboard_l3 = "f5"
fmsx_custom_keyboard_left = "left"
fmsx_custom_keyboard_r = "f3"
fmsx_custom_keyboard_r2 = "ctrl"
fmsx_custom_keyboard_r3 = "escape"
fmsx_custom_keyboard_right = "right"
fmsx_custom_keyboard_select = "f4"
fmsx_custom_keyboard_start = "f1"
fmsx_custom_keyboard_up = "up"
fmsx_custom_keyboard_x = "n"
fmsx_custom_keyboard_y = "m"
fmsx_dos2 = "No"
fmsx_flush_disk = "Immediate"
fmsx_font = "standard"
fmsx_game_master = "No"
fmsx_hires = "Off"
fmsx_log_level = "Off"
fmsx_mapper_type_mode = "Guess"
fmsx_mode = "MSX1"
fmsx_overscan = "No"
fmsx_phantom_disk = "No"
fmsx_ram_pages = "Auto"
fmsx_scci_megaram = "Yes"
fmsx_simbdos = "No"
fmsx_video_mode = "NTSC"
fmsx_vram_pages = "192KB"

but it is also failing for MSX2

**Comment by cayce-msx** [comment]
Still can't reproduce that on my side. I tested:

    openmsx -machine msx2 -ext scc+ -cartb "Gradius 2. Nemesis 2 (1987)(Konami)[SCC][RC-751].rom" # crashes MSX, also for msx1 & msx2plus, and when using '-ext scc'
    
    fmsx -carta "Gradius 2. Nemesis 2 (1987)(Konami)[SCC][RC-751].rom" # works fine, with SCC music
    
    retroarch -L fmsx_libretro.so "Gradius 2. Nemesis 2 (1987)(Konami)[SCC][RC-751].rom" # works fine, with SCC music

I'll first look into the other issue you reported. Maybe something pops up then that also fixes this for you.

**Comment by cayce-msx** [comment]
@Kelvfimer is this issue still present in the latest version? I've not been able to reproduce, and didn't hear back from you if my fix of #119 improved matters. Without further info, I won't be able to help you.

**Comment by Kelvfimer** [comment]
It is working
