### ISSUE TITLE
Lacks support for cassette/disk images

### ISSUE THREAD

**Issue by ensrha** [libretro/fmsx-libretro#13]
Many European games (Feud, Chuckie Egg, etc) weren't released on ROM cartridge, so they're currently not playable.

**Comment by gingerbeardman** [comment]
@ensrha a temporary workaround: https://www.msx.org/news/software/en/dsk2rom-080

I used this to create a custom .dsk to .rom which boots OK

**Comment by gingerbeardman** [comment]
I've added (untested) support for .dsk and .cas file extensions in pull #15

**Comment by ensrha** [comment]
Thanks for the recommendation of dsk2rom. I found the source code at [Vincent's MSX software](http://home.kabelfoon.nl/~vincentd/) and built it for unix. Converted Feud, and it works perfectly. Chuckie Egg loads but isn't really playable since it doesn't support a joystick.

Currently this repository doesn't build, but if I roll back to ae3d93a4a1c37dcd24430a10c9d6fe9f4c60a1f1 and try to load a disk image, it doesn't work. It's still trying to load it as a ROM, I think.

Supporting autoboot also seems necessary since it's very difficult to get anything done with the keyboard in RetroArch.

**Comment by gingerbeardman** [comment]
OK I will have to revert the dsk & was changes and wait for somebody more familiar with the source to step in. Sorry!

**Comment by gingerbeardman** [comment]
@ensrha I've taken a look at the code and I'm actually confident I can do this as soon as my cores are building.

As well as adding the file extension support, I need to branch the filename loading to ROM or DSK depending on the file type

**Comment by gingerbeardman** [comment]
I've completed these changes, will wait until I have working core builds before pushing

**Comment by gingerbeardman** [comment]
@ensrha there are many ways an MSX disc might boot. 

the one i am using has an AUTOEXEC.BAT file.

other methods are listed here: http://www.msxblue.com/manual/dskfaq_c.htm

but really the only way to solve the boot issue is to add a keyboard.

**Comment by gingerbeardman** [comment]
Success with DSK!

Partial success with CAS, more work required.

**Comment by gingerbeardman** [comment]
This has been completed in: https://github.com/libretro/fmsx-libretro/pull/20

**Comment by gingerbeardman** [comment]
@ensrha disk support has been merged, it's the latest nightly. would appreciate your feedback!

**Comment by ensrha** [comment]
Great!

OK, I've tested this using the two example games from my initial post. The Chuckie Egg disk image loads successfully, but the Feud image hangs on a blue screen. For the sake of experiment, I tried to load another two games, 180 and Manic Miner. 180 shows a "Loading, please wait" screen with a small bit of text corruption and hangs. Manic Miner loads successfully. The standalone fmsx displays identical problems using all of these images.

For now, converting the disk images to ROM seems to be the most reliable way of playing them in fmsx.

**Comment by ensrha** [comment]
I'm closing this because the problems that remain seem more likely to be related to the emulation code than the libretro frontend. Thanks for your help.

**Comment by gingerbeardman** [comment]
Great.

I'll do some further investigation anyway.

**Comment by gingerbeardman** [comment]
@ensrha As with all of these old computers there are many different versions of these old games. The first images I tried for your 4 games had the same symptoms as yours. 

I had better luck with the disks from this page: https://www.msx.org/node/44843
All your 4 chosen games work in fMSX with those well packaged and tested disks.

Also, for future reference here's a list of game compatibility for MSX modes: https://en.wikipedia.org/wiki/List_of_MSX_games
