### ISSUE TITLE
fMSX 5.0 released - needs merging

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/fmsx-libretro#28]
fMSX 5.0 released (10 July 2017)

changelog:
https://fms.komkon.org/fMSX/fMSX.html#LABA

source:
https://fms.komkon.org/fMSX/#Downloads

status:
I am having trouble getting 5.0 to run with libretro.
getting it to compile was tricky.

**Comment by gingerbeardman** [comment]
Partial: https://github.com/libretro/fmsx-libretro/pull/29

**Comment by twinaphex** [comment]
Hi there @gingerbeardman,

is this still something we should do? If we do, what do we miss out on in terms of the current commits pushed to master?

Could you perhaps rebase your changes for easier merging?

**Comment by gingerbeardman** [comment]
Current fMSX version is 5.4

**Comment by Darknior** [comment]
Arg so bad you can't finish your port of v5 :(
I have many problems with BlueMSX, many games not working fine ... we have not any good MSX emulator on libretro.

**Comment by gingerbeardman** [comment]
That odd, because BlueMSX is much much better! Check your setup.

**Comment by Darknior** [comment]
@gingerbeardman for sure its a good emulator. But there are not many core settings. I dont remember what emulator ive use by thé past to test and made my set on PC, all the games working fine. Now on batocera with this libretro emulator si many games are not working fine.

**Comment by gingerbeardman** [comment]
tell me one game specifically so I can confirm, then start an issue on that core.

**Comment by Darknior** [comment]
I've try again and many many games and you are right, they working fine for MSX2 and 2+
So strange ...
- Gradius 3 Legend is not working fine, freeze image on ship select but not sound music

**Comment by liberodark** [comment]
5.9 is out and have many fixes http://fms.komkon.org/fMSX/fMSX59.zip

**Comment by gingerbeardman** [comment]
Nice! Over to you @liberodark
