### ISSUE TITLE
No license file included

### ISSUE THREAD

**Issue by prg318** [libretro/fmsx-libretro#30]
The fMSX license should be distributed with this project - no license in indicated for this repo

**Comment by gingerbeardman** [comment]
Please see https://github.com/libretro/fmsx-libretro/blob/master/fMSX/fMSX.html and add a pull for the correct licence file.

**Comment by prg318** [comment]
Could we get a license blurb straight from the author?  I have no problem making the pull request, but I feel more comfortable getting the license text directly from the author.  I don't mean to be a pedant but could you check with the author if he could provide a license text for us to use?  I find two license-like-things in fMSX

From the fMSX.html you linked:
```
fMSX source code is open for everyone to see but it is <U>not</U> in public
domain. You <U>can</U> look and learn from it, but you <U>cannot</U> change
it or copy it without giving a credit to the original author and a few other
conditions. If you would like to port fMSX to another platform or make
changes to the code, <U>please</U>, contact me by email or some other means.
</P>
<P>
You <U>cannot</U> use fMSX source code for commercial purposes
unless you contact me to arrange the conditions of such usage. If your
company intends to use MSX software in its products and you are
considering using fMSX source code, please, email me about licensing.
```

Source code comments:
```
/** fMSX: portable MSX emulator ******************************/
/**                                                         **/
/**                         Menu.c                          **/
/**                                                         **/
/** This file contains runtime menu code for configuring    **/
/** the emulator. It uses console functions from Console.h. **/
/**                                                         **/
/** Copyright (C) Marat Fayzullin 2005-2017                 **/
/**     You are not allowed to distribute this software     **/
/**     commercially. Please, notify me, if you make any    **/
/**     changes to this file.                               **/
/*************************************************************/
```

Including any of these verbatim seems slightly misleading so it might be best to get a license blurb straight for the author to include in this project.  This might be overly pedantic, but I don't want to step on the author's toes in any way

**Comment by gingerbeardman** [comment]
The top one is the licence the author wants to use.

Also see: https://groups.google.com/forum/#!topic/emul8/hEttowf2Vmg

**Comment by gingerbeardman** [comment]
Added in #31

**Comment by gingerbeardman** [comment]
Pull has been merged, please close @prg318

**Comment by prg318** [comment]
Great!  Thanks @gingerbeardman
