### ISSUE TITLE
Feature Request - Ability to map keyboard keys to controller within the Core

### ISSUE THREAD

**Issue by KMFDManic** [libretro/fmsx-libretro#32]
I run this amazing Core on NESC/SNESC!  I previously had this same feature request for the great Commodore 64 (Vice Core), as stated here...

https://github.com/libretro/vice-libretro/issues/7

The end result of that request was perfect for NESC/SNESC   Here is it, in action...Go about 2 minutes in!

https://www.youtube.com/watch?v=dBn9MkHUA_E&feature=youtu.be

Thank you so much for your time and consideration in this Feature Request!  

I love both FMSX and BlueMSX Cores.  I am hoping to get this added to both:)

**Comment by fr500** [comment]
That's not using the generic keymapper, bluemsx has it already and that's the actual generic keymapper unlike the one you showed here.

![image](https://user-images.githubusercontent.com/1721040/33740195-d3b94c8a-db6d-11e7-91e9-fb7632ff6d36.png)

![image](https://user-images.githubusercontent.com/1721040/33740201-d7fd04b2-db6d-11e7-9c1a-56f8376ffb8f.png)

**Comment by fr500** [comment]
Of course you need a recent RetroArch for this, you're using 1.4.1

**Comment by KMFDManic** [comment]
I am actually on 1.6.7 now. That video is from then.

**Comment by fr500** [comment]
![image](https://user-images.githubusercontent.com/1721040/33740894-595bf372-db70-11e7-9ea6-e9b3ba481a18.png)

**Comment by KMFDManic** [comment]
I recorded that video when I was using 1.4.1  I am using RetroArch 1.6.7 now.  The request is to have it just like in Commodore 64 Vice Core, and be able to select the keys.  The actual mapping within the Cores, does not allow all of the keyboard keys to be applied to the controller.  It is limited.  RetroArch 1.6.9, which you did the picture of, has that added better implementation of mapping keyboard controls to a controller?

**Comment by fr500** [comment]
The screenshots I'm showing you are the generic keymapper, it allos to bind gamepad buttons to keys.
Not sure about VICE or anything but that's the generic keymapper people have been discussing, I have implemented it in dosbox, px68k and bluemsx

**Comment by gingerbeardman** [comment]
Similar to #10 which predated the new keymapper

**Comment by KMFDManic** [comment]
@fr500 thanks again for your help in integrating your fantastic keymapper.  We got RetroArch properly updated, and all is perfect, now using the bind method:)
