### ISSUE TITLE
[PS3] Fail to link core to Retroarch

### ISSUE THREAD

**Issue by ofry** [libretro/fmsx-libretro#4]
Log is there: http://pastebin.com/JhqMFR2Y

**Comment by cayce-msx** [comment]
@twinaphex maybe close this one? It's 6 years old, no comments & either fixed by now, or not important..

**Comment by cayce-msx** [comment]
@ofry could you try again, or maybe drop this? On https://www.retroarch.com/?page=platforms it says "Coming soon", and https://buildbot.libretro.com/nightly/playstation/ has no ps3 folder, which implies even RetroArch itself does not support PS3.

**Comment by ofry** [comment]
You can safely drop this. I haven't toolchain for test it now...
