### ISSUE TITLE
Feature request: MSX DiskROM support

### ISSUE THREAD

**Issue by ofry** [libretro/fmsx-libretro#42]
`DISK.ROM     - MSX DiskROM containing BDOS and Disk BASIC (optional)`

This is required for read-write support to disks (example: save smth on MSX disk)

This is related to #40

**Comment by twinaphex** [comment]
@gingerbeardman Hi there, would you perhaps  be interested in implementing this? It would be much appreciated.

**Comment by gingerbeardman** [comment]
Yes, I'll try to make time soon @twinaphex 

@ofry so I understand it, fMSX has supported this feature for a long time. So what is lacking in the libretro port? Just UI to enable the setting (would normally be done on command-line)?

**Comment by ofry** [comment]
First part of this task is add DISK.ROM to firmware list as optional firmware...

**Comment by gingerbeardman** [comment]
Sorry, I'm not sure I follow @ofry 

[The DISK.ROM file is already part of this repo](https://github.com/libretro/fmsx-libretro/tree/master/fMSX/ROMs) and [referenced in the source code](https://github.com/libretro/fmsx-libretro/search?q=disk.rom&unscoped_q=disk.rom).

A PR, or longer description of the problem, would help.

**Comment by gingerbeardman** [comment]
OK, I guess you mean it is not listed in docs?

https://github.com/libretro/docs/blob/master/docs/library/fmsx.md

I have made the edit and filed a PR there: https://github.com/libretro/docs/pull/155/files

This change does not affect or enhance the operation of the emulator core in any way.

Feel free to close this issue if that addresses your initial request.

**Comment by ofry** [comment]
one more:

need to put this to firmware array in fmsx_libretro.info in these repos:

https://github.com/libretro/libretro-super
https://github.com/libretro/libretro-core-info

**Comment by ofry** [comment]
Thanks for help.
