### ISSUE TITLE
Feature request: I/O

### ISSUE THREAD

**Issue by ofry** [libretro/fmsx-libretro#43]
This is related to https://github.com/libretro/fmsx-libretro/issues/40

Now fMSX starts without any disk inside, even if I select "Start Core" (without content).

Proof:

![-181018-223159](https://user-images.githubusercontent.com/11790863/47179707-6a92f000-d327-11e8-9a07-b4010ef09614.png)

**Comment by gingerbeardman** [comment]
This is correct, that is exactly what a real MSX computer does. 

That blue screen is the BASIC prompt, you can type in your own programs and make your own games should you want to.

Please, you need to read up about how an MSX works. This is not an issue/bug but you not having enough experience with the PSX platform.

Please close.

**Comment by ofry** [comment]
Don't understand you.

FILES is MSX DISK BASIC operator.

https://www.msx.org/wiki/FILES

So this screenshot proves in my MSX no disks present at all.

As "disk" I mean 720 kB floppy disk.

**Comment by ofry** [comment]
So why impossible this way?

When we first start any content (or "just core"),

if no disks present, core should create new disk and format it.
I/O on these images should save via libretro SRAM interface.

**Comment by gingerbeardman** [comment]
The core behaves identically to an MSX.

You are asking to change the behaviour of a historical computer system.

Any thoughts @twinaphex ?

**Comment by fr500** [comment]
@ofry seems perfect this way, if you do start core without a disk it doesn't have a disk I don't see a problem.
@gingerbeardman what you could do is leverage the disk control interface to insert disks or whatever.

The idea of using the SRAM interface for saves may sound appealing at first, but remember that you started without content, so the disk wouldn't be tied to a game.

**Comment by ofry** [comment]
@fr500
> The idea of using the SRAM interface for saves may sound appealing at first, but remember that you started without content, so the disk wouldn't be tied to a game. It would be a generic disk that wouldn't be used for the core.

So should be core option "Default disk drives count". (0 - default, can be 0; 1; 2)

**Comment by hizzlekizzle** [comment]
IIRC, Nestopia saves IPS patches that are applied to the pristine disk images to handle saving. Dunno if that's doable/desirable in this case.

**Comment by ofry** [comment]
@gingerbeardman 

Standalone core HAS I/O.

Proof:

![screenshot - 19 10 2018 17_27_55](https://user-images.githubusercontent.com/11790863/47224697-ca8ba400-d3c4-11e8-8243-4388587317ef.png)

**Comment by fr500** [comment]
It also has a wimp gui with mouse and keyboard. That means nothing.
And no, not a core option, disk control interface.

**Comment by ofry** [comment]
It's OK, if I can create and format new disk through libretro interface.

**Comment by ofry** [comment]
Why you close this issue? I know now it can't be implemented without new version of libretro API. But there is a reason to add runtime media control to libretro.

**Comment by cayce-msx** [comment]
@ofry I fully agree with what all others already remarked. You can create a .dsk file yourself (on any *nix variant, including macOS, cygwin and Linux) using 

`dd if=/dev/zero of=empty.dsk ibs=512 count=1440`

Then load empty.dsk as content, and after booting type 

`_format "A:"`

Note that fmsx-libretro also supports .rom and .cas files (well actually, I'll fix #23 shortly) so don't get hung up solely on disks.
