### ISSUE TITLE
Additional Support

### ISSUE THREAD

**Issue by symbios24** [libretro/fmsx-libretro#44]
Hello, is it possible to add support for the Msx TurboR ???

Thanks

**Comment by gingerbeardman** [comment]
You'd have to ask at the source: http://fms.komkon.org/fMSX/

BlueMSX core does support Turbo R. 

Also, just 8 games took advantage of Turbo R:
https://www.msx.org/wiki/MSX_Turbo_R

And the cool GUI operating system, MSX View:
https://youtu.be/sb8n58LoUuA

**Comment by cayce-msx** [comment]
Well, there's actually ~ 201 games: https://www.generation-msx.nl/software/result?q=&searchtype=&sy[]=Turbo-R

But. fMSX just doesn't support Turbo-R; that's not going to happen anymore. And fmsx-libretro is simply a port of fMSX - making sure that the fMSX core runs in RetroArch.

The upside is that openMSX and BlueMSX do a pretty good job at emulating the Turbo-R, and more (like the V9990 video chip). While openMSX has no libretro port, it works very well on e.g. RetroPie.

@twinaphex I'd like to propose to close this issue.
