### ISSUE TITLE
Virtual Keyboard

### ISSUE THREAD

**Issue by luzianscherrer** [libretro/fmsx-libretro#46]
I've used fMSX PSP (http://psp.akop.org/fmsx.htm) before which has a great virtual keyboard that you can use to enter any keyboard input. Shouldn't there also be such a thing in fMSX if run in RetroArch? I don't get how I can do keyboard input which is often needed in games...

**Comment by cayce-msx** [comment]
is this the same as #22 ?

There is a "Keyboard" Control (only for Player 1) but I guess that would not work on a console; it uses the host keyboard which only a full-blown computer has ;)

**Comment by gingerbeardman** [comment]
Yes, it's a dupe of my old #22

**Comment by cayce-msx** [comment]
@twinaphex can you close this as duplicate?

**Comment by cayce-msx** [comment]
@luzianscherrer I know it's been a while but could you, being the reporter, consider closing this as duplicate with #22?

**Comment by luzianscherrer** [comment]
Closing as duplicate of https://github.com/libretro/fmsx-libretro/issues/22
