### ISSUE TITLE
Not the same success loading games as standalone fMSX 4.9

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/fmsx-libretro#48]
- Sometimes a game loads
- Other times you just get to the MSX DOS prompt

From: https://github.com/libretro/fmsx-libretro/issues/47#issuecomment-508887149

Example: Golvellius 2 English DISK B
https://www.generation-msx.nl/software/compile/new-devil-golvellius/translations/1138/

Same DSK file runs OK in fMSX 4.9 standalone

**Comment by Darknior** [comment]
So strange ... have you found why ?
Some bugs already present in 4.9 are always in 5.9 too ...

**Comment by liberodark** [comment]
I think is core lr
