### ISSUE TITLE
Feature Request] Core for Wii

### ISSUE THREAD

**Issue by Edu789** [libretro/fmsx-libretro#51]
Hi there, just wondering why this core is not available on Retroarch for Wii. Any chance it could be made to work on the Wii? Thanks.

**Comment by gingerbeardman** [comment]
It is unfortunate.

Thankfully there is a better MSX emulator for Wii, standalone not RetroArch.

https://wiibrew.org/wiki/BlueMSX-wii

**Comment by Edu789** [comment]
The BlueMsx is bad for having to configure each game to play, it ends up becoming boring, it would be simpler if it had a Retroacrh core...

**Comment by gingerbeardman** [comment]
@Edu789 sure, my point was that you can use BlueMSX _right now_ or you can _wait_ for a RetroArch core.

**Comment by Edu789** [comment]
Ok
