### ISSUE TITLE
where are build errors published?

### ISSUE THREAD

**Issue by cayce-msx** [libretro/fmsx-libretro#70]
@twinaphex I saw that the previous upgrade to 5.9 was reverted due to build failures. Can I (or everyone, rather..) see those build failures? You commented earlier that nightly builds (of all platforms that the cores are built for) can be downloaded via RA. But what if a build fails? Is a build log published somewhere? Or is that on a site only available for appointed maintainers?

I'm asking this because I wouldn't want to burden you with fixing any cross-platform issues introduced by me in the upgrade process, that I wouldn't be able to see locally.

**Comment by twinaphex** [comment]
Hi, is this still relevant? Or can we close this?

**Comment by cayce-msx** [comment]
Well, if there is any way I could see build logs for all platforms that fmsx-libretro is being built on, that would be awesome. (I was hoping you knew & could supply some URLs, for example.) But if those logs are not accessible then it's okay to close this issue.
