### ISSUE TITLE
Feature request: Add option to SRAM-ify I/O

### ISSUE THREAD

**Issue by ofry** [libretro/fmsx-libretro#90]
I mean: Instead of actual saving modified *.dsk image, core should save only diff patch and put it through SRAM interface to *.srm file. So, if save state SRAM save support is ON (by default), it should be patched in memory after loading save state.

**Comment by ofry** [comment]
Something like it, as I heared, was in FCEUmm core when using FDS mode.

**Comment by ofry** [comment]
Related to #40

**Comment by gingerbeardman** [comment]
Cool idea!

**Comment by cayce-msx** [comment]
@twinaphex please advise before I submit a PR that would only be rejected. Options:
- use `retro_get_memory_data(RETRO_MEMORY_SAVE_RAM)` to persist generated IPS to .srm: has **dynamic** size - is that supported?
- same, but persist .dsk (720KiB per disk): might be too large? fceumm does: `if (GameInfo->type == GIT_FDS) return FDSROM_ptr()` - is that the complete image, and how large can that be? Feels like waste, to duplicate all data.
- save .IPS files: requires `need_fullpath=false` for soft-patching and will _not_ work for multi-disk, which is the most obvious use case
- keep current behaviour: update .dsk when user enables applicable option (which 'taints' the user's game collection), plus support SRAM saves (supported by a subset of MSX games)
- ?? any other ideas?
Thanks in advance for any tips/suggestions!

**Comment by ofry** [comment]
@cayce-msx Twinaphex isn't responding, even in Discord. Could you just make the PR and see, will anyone from libretro team will merge it?

**Comment by twinaphex** [comment]
Hi there @cayce-msx , I'd prefer going through the first option if possible -

> use retro_get_memory_data(RETRO_MEMORY_SAVE_RAM) to persist generated IPS to .srm: has dynamic size - is that supported? Plus: cores don't get signalled when the SRAM is read back from disk, or do they?

It'd be best not to have any kind of disk-based file I/O going on at all and do it strictly in-memory through the API functions.

**Comment by ofry** [comment]
@twinaphex If game requires save to inserted disk, why it can't be handled by SRAM interface?

**Comment by ofry** [comment]
So is your objection against dynamic-size .srm files?

**Comment by ofry** [comment]
`save .IPS files: requires need_fullpath=false for soft-patching and will not work for multi-disk, which is the most obvious use case` - can't we handle ips patches for each disk in M3U?

**Comment by cayce-msx** [comment]
Aw - I'd just finished a solution using disk-based file I/O 10 days ago - and then the message above appeared. (I was busy with other things the past 10 days) I've now pushed that non-preferred solution to https://github.com/cayce-msx/fmsx-libretro/tree/fileio-based-patching for anyone interested. I'll restart with the suggested approach. 

But first I have to find out how the SRAM API works. My 2 questions above have not been answered. So that might take some time, if I have to figure all of that out myself, with documentation being quite sparse...

**Comment by cayce-msx** [comment]
@ofry @twinaphex a PR for this is now available. I dropped the IPS 'compression'; the dynamic SRAM size issue bothered me too much. If it's an issue, maybe compressing .srm files within RetroArch could be contemplated? (Note: .state files _are_ compressed.) I tested a few situations, but didn't do rigorous testing. Note that for multidisk games, about 22MiB RAM is malloc'd to accomodate the maximum 32 .dsk images in memory, when this new option is enabled. Is that workable for all platforms? At any rate, this solution doesn't invoke any custom file I/O.

Let me know what you think of this!

**Comment by cayce-msx** [comment]
Note: this'll be my last contribution for the coming months; I'll be working on another project. It's been fun to contribute to fmsx-libretro! Every few weeks I'll check in to see if any issues have been reported on code I contributed. New features will have to wait until later.

**Comment by gingerbeardman** [comment]
Amazing work you have done here @cayce-msx thanks so much and best of luck! 

What project are you working on next if you don't mind me asking?

**Comment by cayce-msx** [comment]
@ofry the PR is merged some time now, Could you verify and if possible close this issue?

**Comment by cayce-msx** [comment]
@ofry feedback on this functionality is still appreciated. Does it satisfy your request? It'd be great if this issue could be closed.

**Comment by ofry** [comment]
@cayce-msx I will test it soon. Please give me more time.

**Comment by ofry** [comment]
Thank you very much!
