### ISSUE TITLE
“fmsx_libretro.info” on buildbot needs to be updated for .m3u support

### ISSUE THREAD

**Issue by haojiezhu** [libretro/fmsx-libretro#95]
Not sure if this is the right place to report this issue. While .m3u support was already in the latest core update, “fmsx_libretro.info” from buildbot (inside https://buildbot.libretro.com/assets/frontend/info.zip) wasn’t updated and doesn’t include .m3u in “supported_extensions”. This prevents the core from loading .m3u or showing “Disc Control” in Quick Menu.

I manually added .m3u to “fmsx_libretro.info” and tested a few multi-disk games on Windows and Android, including "Dead of the Brain", “Snatcher”, and “SD Snatcher”. m3u loading and disk swapping both worked correctly in these games. Maybe someone can update “fmsx_libretro.info” on buildbot.

**Comment by gingerbeardman** [comment]
That file is here https://github.com/libretro/libretro-super/blob/master/dist/info/fmsx_libretro.info if you want to update and open a Pull Request to get that changed accepted.
