### ISSUE TITLE
DSK images don't work

### ISSUE THREAD

**Issue by freq-mod** [libretro/fmsx-libretro#96]
As of cd2d59a I can't load anything in .dsk format, be it demo or game (Sonyc). All required firmware ROMs are present.

**Comment by cayce-msx** [comment]
@freq-mod could you provide a bit more details? Works fine on my machine ;) Have you tried a build _after_ cd3d59a? 
If that also fails: I'd like to know what platform you use, which .dsk images, do .rom files still work, what version of RetroArch & libretro-fmsx. If at all possible, please provide logs - see https://docs.libretro.com/guides/generating-retroarch-logs/

**Comment by freq-mod** [comment]
I have two devices: Anbernic RG351 (64-bit ARM Linux) with RetroArch 1.9.13, fMSX ver 4.9. only ROM works, dsk files don't - machine boots to MSX BASIC, nothing happens then.
Second device is Powkiddy V90 (Miyoo/Bittboy, ARM Linux) with RetroArch 1.9.14, fMSX 6.0 cd2d59a. The same as above - ROMs work fine, DSKs don't the same way as above. 
[dsk.zip](https://github.com/libretro/fmsx-libretro/files/7763431/dsk.zip) - dsk files I used for testing. Didn't test newer version yet, and I personally don't see anything suspicious in logs.

**Comment by freq-mod** [comment]
Update: newest build doesnt work either, it seems

**Comment by cayce-msx** [comment]
Thanks, I'll try to reproduce your problem with that info. 

Regarding 4.9: there was a long-standing bug in that version that would only open .dsk files, not .DSK... And the same for .rom vs. .ROM. Fixed in 6.0. Does upgrading fMSX in your Anbernic device solve that issue? (your Powkiddy should not have that problem; I'll see what I can do)

**Comment by freq-mod** [comment]
Well, updating fMSX in Anbernic won't be an option likely, because RetroArch is as a part of ELEC system, so I can't just drop in an updated core, more steps would have to be done. Still - even on Windows 11 I have the same problem, fyi

**Comment by cayce-msx** [comment]
That's odd.. All three work fine on my local build on Linux (x86) and RetroPie (ARM7). Didn't try yet on Windows (10 in my case); will do that asap.

I'll add some debug logging code back (was removed by the maintainer to get rid of stdout interaction) to have a bit more to go on in the future. 

Apologies - I know very little of the plethora of devices that RetroArch runs on. I've actually never heard of Anbernic nor Powkiddy. So I'm not acquainted with how easy it is to update etc. Would it be possible for you to build & install a custom version on the Powkiddy if I created a branch with some extra debug logging, to get to the bottom of this?

In the meantime, could you try renaming the files to lower case (if that's not already so) and making sure the platform is set to MSX2+? Sonyc fails if that isn't the case; the other two work fine on MSX2. 

I _did_ notice Sonyc horizontal scrolling is totally broken on fmsx-libretro. It looks fine on openMSX. That'll be another bug, I suppose...

**Comment by freq-mod** [comment]
>Would it be possible for you to build & install a custom version on the Powkiddy if I created a branch with some extra debug logging, to get to the bottom of this?

I think yes, at worst I will just ask for compiling tips if I jump into some roadblock. I have a toolchain, so it shouldn't be too problematic I hope...
p.s. changing filenames to lower case and seeting machine to msx2+ doesnt help

**Comment by cayce-msx** [comment]
One last thought before I start adding log code: could it be that your disk rom isn't loaded somewhow? I forgot to ask what you actually _do_ see when starting .dsk images and being presented with a prompt. Do you just see "MSX BASIC version x.y" or also "Disk BASIC version 1.0"?

The DISK.ROM must be named like that (capitals!). The standard one has SHA1 032cb1c1c75b9a191fa1230978971698d9d2a17f. Location: same as MSX2EXT.ROM MSX2PEXT.ROM MSX2P.ROM MSX2.ROM MSX.ROM; the RA system folder.

Loading the disk ROM can actually be influenced at boot time by holding Ctrl or Shift (that's not an emulator addition - also in real MSXs). One of my PRs adds code to 'virtually' press shift during boot to skip loading DiskROM. Most tape games need the extra memory. That code should only be active when loading a .CAS image, though.

**Comment by freq-mod** [comment]
OK, so DISK.ROM was the problem. Now everything works fine

**Comment by cayce-msx** [comment]
Great! Good to hear that. Happy gaming!

Could you close this issue? I don't have rights for that.

**Comment by cayce-msx** [comment]
Great! Good to hear that. Happy gaming!
